spring.application.name=Daki-Shop
server.port=8081

spring.datasource.url=jdbc:h2:mem:dakishopdb
spring.datasource.driverClassName=org.h2.Driver
spring.H2.console.enabled=true
spring.datasource.username=sa
spring.datasource.password=haddou
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



