spring.application.name=Daki-Shop
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/test_tuto
spring.datasource.username=postgres
spring.datasource.password=postgresql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



